### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by langner**

### CODE REVIEW

**Comment by langner** [comment]
Why no merge? I thought that was a typo.

**Comment by egonw** [comment]
I didn't "merge", but instead applied your patch using "cherry-pick". That has the advantage of keeping a linear history... here's your patch:

https://github.com/egonw/cml-schema/commit/577a61d802143c89036cfc169b78ecdadb360321

**Comment by langner** [comment]
I understand. There is also a _disadvantage_ of cherry-picking: a new commit (hash) is created, so if I merge your repo back into mine I will have two identical commits in the history. If this happens many times, things get dirty.

You can keep a linear history without duplicating commits by doing something like `git add remote to_merge ...; git rebase to_merge/master`, which is unproblematic unless the histories have diverged.

**Comment by egonw** [comment]
OK, was not aware of that cherry-pick changed the commit, but makes sense... I'll consider your suggested approach!

**Pull request closed without merging**
